/*
 * action types
 */

export const ADD_RECORD = 'ADD_RECORD'
export const TRANSACT_RECORD = 'TRANSACT_RECORD'
export const SELECT_RECORDS = 'SELECT_RECORDS'
export const REQUEST_RECORDS = 'REQUEST_RECORDS'
export const RECEIVE_RECORDS = 'RECEIVE_RECORDS'

export const SELECT_PATIENT = 'SELECT_PATIENT'
export const REQUEST_PATIENTS = 'REQUEST_PATIENTS'
export const RECEIVE_PATIENTS = 'RECEIVE_PATIENTS'
