/*
 * action types
 */

export const TRANSACT_RECORD = 'TRANSACT_RECORD'
export const SELECT_RECORDS = 'SELECT_RECORDS'
export const REQUEST_RECORD_INVOKATION = 'REQUEST_RECORD_INVOKATION'
export const REQUEST_RECORDS = 'REQUEST_RECORDS'
export const RECEIVE_RECORDS = 'RECEIVE_RECORDS'

export const SELECT_ORG = 'SELECT_ORG'
export const REQUEST_INIT_DATA = 'REQUEST_INIT_DATA'
export const RECEIVE_ORGS = 'RECEIVE_ORGS'
export const SELECT_WALLET = 'SELECT_WALLET'
export const RECEIVE_WALLET = 'RECEIVE_WALLET'
export const RECEIVE_WALLET_RECORDS = 'RECEIVE_WALLET_RECORDS'

export const SUBMIT_LOGIN = 'SUBMIT_LOGIN'
export const SUBMIT_REGISTER = 'SUBMIT_REGISTER'
export const MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS'

export const REQUEST_ALL_PERMISSIONS = 'REQUEST_ALL_PERMISSIONS'
export const RECEIVE_ALL_PERMISSIONS = 'RECEIVE_ALL_PERMISSIONS'
export const REQUEST_ALL_IDS = 'REQUEST_ALL_IDS'
export const RECEIVE_ALL_IDS = 'RECEIVE_ALL_IDS'
